name: build

on:
  push:
    branches:
    tags:
      - v*
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Detect version
        run: |-
          VERSION="development"
          if [[ "${{ env.GITHUB_REF_TYPE }}" == "tag" ]]; then
            VERSION=${{ env.GITHUB_REF_NAME }}
          fi
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Running tests
        uses: docker/build-push-action@v6
        with:
          target: test
          push: false
          build-args: |
            VERSION=${{ env.VERSION }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build production image
      #   uses: docker/build-push-action@v6
      #   with:
      #     target: production
      #     push: ${{ env.GITHUB_REF_TYPE == "tag" }}
      #     build-args: |
      #       VERSION=${{ env.VERSION }}
      #     tags: ghcr.io/blackskad/go-web-scaffold:${{ env.VERSION }}
